### ISSUE TITLE
DBusException after two news items

### ISSUE THREAD

**Issue by NeuroWinter** [srcecde/desktop-news-notifier#1]
I get this after the 2nd news item:

Traceback (most recent call last):
  File "/home/neuro/bin/news.py", line 42, in <module>
    Parsefeed()
  File "/home/neuro/bin/news.py", line 36, in Parsefeed
    n.show()
  File "/usr/lib/python2.7/site-packages/notify2.py", line 188, in show
    self.timeout,  # expire_timeout
  File "/usr/lib64/python2.7/site-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib64/python2.7/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name :1.24 was not provided by any .service files

**Comment by NeuroWinter** [comment]
Just adding a try catch solved this.
